# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-c-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install C build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
            build-essential \
            lcov

      - name: Build, run C tests & generate coverage
        working-directory: firmware/stm32-i2c-sensor-hub/tests
        run: |
          make clean
          make all
          make coverage-html

      - name: Upload C coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: firmware/stm32-i2c-sensor-hub/tests/coverage.info
          flags: c

      - name: Upload coverage-info artifact
        uses: actions/upload-artifact@v3
        with:
          name: c-coverage-info
          path: firmware/stm32-i2c-sensor-hub/tests/coverage.info

      - name: Upload coverage HTML artifact
        uses: actions/upload-artifact@v3
        with:
          name: c-coverage-html
          path: firmware/stm32-i2c-sensor-hub/tests/coverage-report/
