# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-c-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Smoke-test gcc
        run: gcc --version

      - name: Install C build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
            build-essential \
            lcov

      - name: Build and run C tests
        working-directory: firmware/stm32-i2c-sensor-hub/tests
        run: |
          make clean
          make all
          ./test_response_runner
          ./test_drivers_runner
