# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  python-tests:
    name: Python Tests & Coverage
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: 1

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install all Python dependencies
        working-directory: master
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .[dev]

      - name: Run pytest across both codebases
        run: |
          pytest \
            firmware/stm32-i2c-sensor-hub/scripts/tests \
            master/tests \
            --cov=firmware/stm32-i2c-sensor-hub/scripts \
            --cov=master \
            --cov-report=xml:python-coverage.xml \
            --cov-report=term-missing

      - name: Upload Python coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: python-coverage.xml
          flags: py
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  c-tests:
    name: C Tests & Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install C build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
            build-essential \
            lcov

      - name: Build, run C tests & generate coverage
        working-directory: firmware/stm32-i2c-sensor-hub/tests
        run: |
          make clean
          make all
          make coverage-html

      - name: Upload C coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: firmware/stm32-i2c-sensor-hub/tests/coverage.info
          flags: c
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage-info artifact
        uses: actions/upload-artifact@v4
        with:
          name: c-coverage-info
          path: firmware/stm32-i2c-sensor-hub/tests/coverage.info

      - name: Upload coverage HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: c-coverage-html
          path: firmware/stm32-i2c-sensor-hub/tests/coverage-report/
